project:
  type: website
  output-dir: docs

website:
  title: "Gapminder Data Analysis"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Life Expectancy and GDP per Capita"
        href: life-gdp.qmd
      - text: "Life Expectancy and Population"
        href: life-population.qmd
      - text: "Country Analysis"
        href: country.qmd
      - text: "Interactive Map"
        href: interactive-map.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true



